### ISSUE TITLE
Mod built against 1.20.2 fails when pre-20.2 mixin runs due to failed remapping

### ISSUE THREAD

**Issue by Linguardium** [enjarai/cicada-lib#1]
texturesLoaded doesnt exist in 1.20.2 so when building the mod targetting 1.20.2, the mixin wont have the shadowed field mapped properly and cicada will crash when loaded on 1.20.1 due to trying to load a partially remapped class

**Comment by enjarai** [comment]
Ah, that does make sense now that I actually think about it. Thanks for letting me know. I've taken down pre-1.20.2 versions of Do a Barrel Roll while I figure out how I want to handle this.

**Comment by enjarai** [comment]
Fixed by converting to a proper multiversion project.
