### ISSUE TITLE
CICADA is not working PLS HELP ME

### ISSUE THREAD

**Issue by vitamin281** [enjarai/cicada-lib#2]
I'm trying to use the do a barrel roll mod and i have to use cicada but it keeps saying using the wrong version when I'm not, also im on fb 1.21.1
![image_2024-08-30_163731330](https://github.com/user-attachments/assets/377197ba-bec7-4357-b094-f8a15244bc55)

**Comment by enjarai** [comment]
Make sure you have [this exact version](https://modrinth.com/mod/cicada/version/0.8.3+1.21-and-above). If that doesn't work, please send a screenshot of your instance configuration and a copy of your latest log.

**Comment by vitamin281** [comment]
thank you 
apparently curseforge did not have the correct version
